name: Build & Push Backend Images

on:
  push:
    branches: [ master ]
    paths:
      -  "backend/**"
      -  "cd/**"
      - ".github/workflows/**"
      - "frontend/**"

env:
  AWS_REGION: us-east-2
  ECR_REGISTRY: 589335871756.dkr.ecr.us-east-2.amazonaws.com

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - ai-service
          - oms-service
          - portfolio-service
          - blotter-service

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::589335871756:role/GithubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push ${{ matrix.service }}
        run: |
          docker build \
            -f backend/${{ matrix.service }}/Dockerfile \
            -t ${{ matrix.service }} \
            .

          docker tag ${{ matrix.service }}:latest \
            $ECR_REGISTRY/${{ matrix.service }}:latest

          docker push \
            $ECR_REGISTRY/${{ matrix.service }}:latest
