# name: Build & Push to ECR

# on:
#   push:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Login to ECR
#         run: |
#           aws ecr get-login-password \
#           | docker login \
#             --username AWS \
#             --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com

#       - name: Build image
#         run: |
#           docker build -t ai-service .

#       - name: Tag image
#         run: |
#           docker tag ai-service:latest \
#           123456789012.dkr.ecr.us-east-1.amazonaws.com/ai-service:latest

#       - name: Push image
#         run: |
#           docker push \
#           123456789012.dkr.ecr.us-east-1.amazonaws.com/ai-service:latest
